spring.application.name=Farm2Door
spring.main.allow-circular-references=true

# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.username=${SPRING_DATABASE_USERNAME}
spring.datasource.password=${SPRING_DATABASE_PASSWORD}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#(create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update

api.prefix = /api/v1

# JWT Configuration
auth.token.expirationInMils = 3600000
auth.token.jwtSecret = ${JWT_SECRET}

spring.config.import=optional:file:.env[.properties]
